//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasWPF
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;

    public partial class Usuarios
    {
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cargo { get; set; }
        public string Email { get; set; }
        public static async Task<bool> AgregarUsuario(Usuarios usu)
        {

            using (var cliente = new HttpClient())
            {
                cliente.BaseAddress = new Uri("https://localhost:44331/");
                cliente.DefaultRequestHeaders.Accept.Clear();
                cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await cliente.PostAsJsonAsync("api/Usuarios", usu);
                return response.IsSuccessStatusCode;
            }
        }

        public static async Task<List<Usuarios>> ObtenerUsuario()
        {

            List<Usuarios> lstUsuario = new List<Usuarios>();


            using (var cliente = new HttpClient())
            {

                cliente.BaseAddress = new Uri("https://localhost:44331/");


                cliente.DefaultRequestHeaders.Accept.Clear();

                cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = await cliente.GetAsync("api/Usuarios");




                if (response.IsSuccessStatusCode)
                {

                    lstUsuario = await response.Content.ReadAsAsync<List<Usuarios>>();
                }
            }


            return lstUsuario;
        }

        public override string ToString()
        {
            return this.Nombre;
        }

    }
}
